import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function analyzeAudioKey(audioBase64: string, mimeType: string) {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: [
        {
          parts: [
            {
              inlineData: {
                data: audioBase64,
                mimeType: mimeType,
              },
            },
            {
              text: "Analyze this audio sample. Identify the fundamental frequency (Hz) and the musical key (e.g., C Major, A Minor). Return ONLY a JSON object with keys: 'frequency', 'key', 'noteName', 'confidence'.",
            },
          ],
        },
      ],
      config: {
        responseMimeType: "application/json",
      },
    });

    return JSON.parse(response.text || "{}");
  } catch (error) {
    console.error("Error analyzing audio:", error);
    return null;
  }
}

export function generateAbletonScript(fundamentalNote: string, targetInterval: string) {
  return `
# Ableton Live Python Script (Simpler Tuner)
# Generated by Harmonic Simpler AI

import Live
from Ability.SimplerDevice import SimplerDevice

def tune_simpler_to_interval(track_index, device_index, interval_name):
    """
    Intervals: '3rd_up', '3rd_down', '5th_up', '5th_down', '6th_up', '6th_down'
    """
    song = Live.Base.get_song()
    track = song.tracks[track_index]
    device = track.devices[device_index]
    
    if device.class_name != 'SimplerDevice':
        return "Device is not a Simpler"

    # Interval semitones
    intervals = {
        '3rd_up': 4,
        '3rd_down': -4,
        '5th_up': 7,
        '5th_down': -7,
        '6th_up': 9,
        '6th_down': -9
    }
    
    semitones = intervals.get(interval_name, 0)
    
    # Access the 'Transpose' parameter of Simpler
    # In LOM (Live Object Model), this is usually parameter index 1 or 2
    for param in device.parameters:
        if param.name == 'Transpose':
            param.value = semitones
            break
            
    return f"Tuned to {interval_name} ({semitones} semitones)"

# Example usage:
# tune_simpler_to_interval(0, 0, '${targetInterval}')
`;
}
